package com.citi.euces.sitiouec.infra.utils;

public class MensajesUtils {
	
	public static final String NO_REGISTROS="NO SE ENCONTRARON REGISTROS CON LOS VALORES SELECCCIONADOS";
	
	public static final String FECHAELIMINAREXITO="FECHA BORRADA CON EXITO";
	
	public static final String CONTRATOREPETIDOEXITO="CONTRATOS REPETIDOS BORRADOS CON EXITO";
	
	public static final String ELIMINADOCONEXITO="INFORMACION ELIMINADA CON EXITO";
	
	public static final String CLIENTESREPETIDOSEXITO="CLIENTES REPETIDOS BORRADOS CON EXITO";
	
	public static final String FECHAGUARDADOEXITO="FECHA GUARDADA CON EXITO";
	
	public static final String FAVORVALIDAR="ERROR AL INSERTAR LOS REGISTROS, FAVOR DE VALIDAR";	
	
	public static final String NOSEENCONTROID="ERROR, ID NO EXISTENTE";	
	
	public static final String SOEIDNOENCONTRADO="NOMBRE DE EL SOEID NO ENCONTRADO, FAVOR DE VALIDAR";	
	
	public static final String NOSEENCONTRARONREGISTROSCIENTES="NO SE ENCONTRARON REGISTROS, VALIDAR RANGO DE FECHAS";
	
	public static final String SOLICITUDACTUALIZADAEXITO ="ACTUALIZACION KPI COMPLEMENTO EXITOSA";
	
	public static final String NOSEENCONTRARONREGISTROSCONTRATOS="NO SE ENCONTRARON REGISTROS, VALIDAR RANGO DE FECHAS";
	
	public static final String SINREGISTROS="NO SE ENCONTRARON REGISTROS CON LA DESCRIPCION SOLICITADA";
	
	public static final String NOSENCONTRARONREGISTROS ="NO SE ENCONTRARON REGISTROS, VALIDAR RANGO DE FECHAS";
	
	public static final String FECHAEDITADAEXITO ="FECHA EDITADA CON EXITO";
	
	public static final String TIMElINESSEXITO="LOS POSIBLES FUERA DE TIEMPO HAN SIDO ALMACENADOS CORRECTAMENTE";
	
	public static final String REPROCESOEXITO="LOS POSIBLES REPROCESO SIDO ALMACENADOS CORRECTAMENTE";
	
	public static final String REGISTROSEXITO="REGISTROS ELIMINADOS CON EXITO";	
	
	public static final String NOSEENCONTRARONREGISTROSCETES="NO SE ENCONTRARON REGISTROS CETES";
	
	public static final String NOSEENCONTRARONREGISTROSSUBASTAS="NO SE ENCONTRARON REGISTROS";
	
	public static final String NOSENCONTRARONREGISTROSEJECUTIVOS ="NO SE ENCONTRARON REGISTROS, VALIDAR PARAMETROS DE ENTRADA";
	
	public static final String INSERTARHISTORICOASIGNACIONES="REGISTROS INSERTADOS CORRECTAMENTE";
	
	public static final String ACTUALIZACIONOK="REGISTROS ACTUALIZADOS CORRECTAMENTE";
	
	public static final String SOEIDACTUALIZADOS="SOEID ACTUALIZADOS CORRECTAMENTE";
	
	public static final String SINUSUARIOSACTIVOS ="NO SE ENCONTRARON REGISTROS DE USUARIOS ACTIVOS";
	
	public static final String EJECUTIVONOPUEDERECIBIR ="EJECUTIVO NO ACTIVO";
	
	public static final String SINREGISTROSLISTA ="NO SE ENCONTRARON REGISTROS";
	
	public static final String CLIENTESNOACTULIZADOS ="NO SE ENCONTRARON CLIENTES POR ACTUALIZAR";
	
}
